# Generated by Django 6.0.2 on 2026-02-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('story_title', models.CharField(max_length=200)),
                ('story_content', models.TextField()),
                ('story_image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
