# Generated by Django 6.0.2 on 2026-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=300)),
                ('subtext', models.TextField()),
                ('primary_button', models.CharField(max_length=50)),
                ('secondary_button', models.CharField(max_length=50)),
                ('hero_image', models.ImageField(upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
