# Generated by Django 6.0.2 on 2026-02-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_preview/'),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.CreateModel(
            name='CourseLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_points', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='course_tech_icons/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='courses.course')),
            ],
        ),
    ]
