# Generated by Django 6.0.2 on 2026-02-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_certification_course_fee_course_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='detail_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
