# Generated by Django 6.0.2 on 2026-02-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_detail_description_course_detail_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mode',
        ),
        migrations.AddField(
            model_name='course',
            name='available_modes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
