# Generated by Django 6.0.2 on 2026-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
