# Generated by Django 6.0.2 on 2026-02-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_whychooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='why_section/')),
                ('circle_text', models.CharField(default='Why choose Us', max_length=50)),
            ],
        ),
    ]
