# Generated by Django 6.0.2 on 2026-02-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='resume_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
